### ISSUE TITLE
refract-cms.com down & run issues

### ISSUE THREAD

**Issue by ManAnRuck** [alexbechmann/refract-cms#147]
Hi, i am searching for an React Typescript CMS and found this :)

but I have some issues.
1. https://refract-cms.com/ looks down
2. `npx @refract-cms/create-app --dir my-refract-cms`
result `Cannot find module 'commander'`
3. clone this and `yarn install` & `yarn dev`
a lot of @refract-core not found

<img width="957" alt="Bildschirmfoto 2020-07-17 um 11 11 18" src="https://user-images.githubusercontent.com/2183135/87769678-4460f380-c81e-11ea-93ee-0ea0c641cbb5.png">

node: 8 & 12 & 14 tested
OS: macOS

**Comment by alexbechmann** [comment]
Hi @ManAnRuck. 

I apologise for the misleading information & delayed response!

The repo has moved to <https://github.com/refract-cms/refract-cms> along with some refactoring & tidyup.

You can get started with the instructions in the revised README.

Unfortunately the website is still down, and i hope to have a new docs site available in the near future. Please create a new issue on the new repo for this!
